plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'com.gradleup.shadow'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

sourceSets {
    main {
        java {
            srcDir project(':common').file('src/main/java')
            exclude 'indi/etern/musichud/client/ui/components/**'
            exclude 'indi/etern/musichud/client/ui/pages/**'
            exclude 'indi/etern/musichud/client/ui/screen/MainFragment.java'
            exclude 'indi/etern/musichud/client/ui/utils/ButtonInsetBackgroundFactory.java'
            exclude 'indi/etern/musichud/client/ui/utils/EasingInterpolator.java'
            exclude 'indi/etern/musichud/client/ui/utils/SpringInterpolator.java'
            exclude 'indi/etern/musichud/mixin/SpanSetMixin.java'
        }
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name "JitPack"
        url 'https://jitpack.io'
    }
    maven {
        name "IzzelAliz Maven"
        url "https://maven.izzel.io/releases/"
    }
    flatDir {
        dir rootProject.file('libs')
    }
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

neoForge {
    version = rootProject.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "$rootProject.archives_name" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:$rootProject.forge_config_api_port_version"

    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation "com.github.umjammer:jlayer:$rootProject.jlayer_version"
    shadowBundle "com.github.umjammer:jlayer:$rootProject.jlayer_version"

    implementation "org.jflac:jflac-codec:$rootProject.jflac_version"
    shadowBundle "org.jflac:jflac-codec:$rootProject.jflac_version"

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

//    implementation "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
//    shadowBundle "io.github.selemba1000:JavaMediaTransportControls:$rootProject.jmtc_version"
    implementation "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-core:$rootProject.dbus_version"

    implementation "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
    shadowBundle "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$rootProject.dbus_version"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    exclude 'org/slf4j/**'
}

jar {
    dependsOn shadowJar
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(zipTree(shadowJar.archiveFile))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
